# Generated by Django 4.2.7 on 2023-11-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeobservations',
            unique_together={('store_id', 'timestamp_utc')},
        ),
    ]
