# Generated by Django 4.2.7 on 2023-11-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_storeobservations_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('IN_PROCESS', 'IN_PROCESS'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=100)),
                ('report_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_retry_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='store_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
