# Generated by Django 4.2.7 on 2023-11-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_alter_storetimezone_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebusinesshours',
            name='day_of_week',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='storebusinesshours',
            name='end_time_local',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='storebusinesshours',
            name='start_time_local',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='storebusinesshours',
            name='store_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storeobservations',
            name='status',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='storeobservations',
            name='timestamp_utc',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='store_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='timezone_str',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
